#PostgreSQL configuration
version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_USER:db_user
      - POSTGRES_PASSWORD:password
      - POSTGRES_DB:controls
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data