# Generated by Django 3.0 on 2019-12-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('maximum_rabi_rate', models.FloatField()),
                ('polar_angle', models.FloatField()),
            ],
        ),
    ]
